// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config';

// Enable verbose auth logging
const DEBUG_AUTH = true;

// Extract project reference from the URL
const getProjectRef = () => {
  try {
    const url = new URL(SUPABASE_URL);
    return url.hostname.split('.')[0];
  } catch {
    return 'unknown';
  }
};

const PROJECT_REF = getProjectRef();
const STORAGE_KEY = `sb-${PROJECT_REF}-auth-token`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client with standard localStorage storage
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      storageKey: STORAGE_KEY,
      debug: DEBUG_AUTH
    },
    global: {
      headers: {
        'X-Client-Info': 'ugclive-frontend'
      }
    }
  }
);

// Diagnostic function to check auth state
export const diagnoseAuthState = async () => {
  try {
    console.log('[AUTH] Running auth diagnostic...');
    
    // Check for auth token in localStorage
    const localStorageToken = localStorage.getItem(STORAGE_KEY);
    console.log('[AUTH] Token exists in localStorage:', !!localStorageToken);
    
    // Try to get current session
    const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
    console.log('[AUTH] Current session:', sessionData?.session ? 'Valid' : 'None');
    if (sessionError) {
      console.error('[AUTH] Session error:', sessionError);
    }
    
    // Try to get current user
    const { data: userData, error: userError } = await supabase.auth.getUser();
    console.log('[AUTH] Current user:', userData?.user ? `${userData.user.email}` : 'None');
    if (userError) {
      console.error('[AUTH] User error:', userError);
    }
    
    // Log all auth-related storage items
    console.log('[AUTH] Auth storage items:');
    Object.keys(localStorage).forEach(key => {
      if (key.includes('supabase') || key.includes('sb-') || key.includes('auth')) {
        const value = localStorage.getItem(key);
        console.log(`  ${key}: ${value ? `${value.substring(0, 20)}...` : 'empty'}`);
      }
    });
    
    return {
      hasToken: !!localStorageToken,
      hasSession: !!sessionData?.session,
      hasUser: !!userData?.user,
      sessionError,
      userError,
      contextState: {
        user: userData?.user ? { email: userData.user.email, id: userData.user.id } : null,
        session: sessionData?.session ? { expires_at: sessionData.session.expires_at } : null
      }
    };
  } catch (error) {
    console.error('[AUTH] Diagnostic error:', error);
    return { error };
  }
};

// Enable realtime functionality
export const enableRealtimeForGeneratedVideos = async () => {
  try {
    await supabase
      .channel('generated_videos_changes')
      .subscribe((status) => {
        console.log('Realtime subscription status:', status);
      });
    console.log('Realtime subscription initialized for generated_videos');
  } catch (error) {
    console.error('Error enabling realtime:', error);
  }
};
